### ISSUE TITLE
[morpheusvm/tokenvm] move `integration` helpers to a shared package

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#264]
Blocked: #258

**Comment by lazyfuhrer** [comment]
Assign me @patrick-ogrady

**Comment by patrick-ogrady** [comment]
As mentioned in the description, this is blocked on #258. Once that is merged (hopefully today), you should be g2g.

**Comment by patrick-ogrady** [comment]
I would recommend creating a `ci` package in the root of repo. In there, you should extract common helpers that could be used by anyone writing integration tests in this style.

You should not copy the existing integration tests there.

**Comment by Dimitar-St** [comment]
Hello @patrick-ogrady, 

Can I get this issue, looked around the integration tests and took into consideration your advise for the testing package and started a sample implentation. Would be pleasure to work on it.

**Comment by patrick-ogrady** [comment]
Go ahead! I haven't spent any time on this and don't plan to in the short term.

There are some new patterns we started using in AvalancheGo/subnet-evm when we set up the Teleporter integration tests if you are looking for inspiration.

**Comment by Dimitar-St** [comment]
Okay, for sure will look it up, thanks a lot!

**Comment by Dimitar-St** [comment]
Hello @patrick-ogrady,

Do you have any tips on how to buid the project because my development cycle is really tidious. It always say that the blst.h is nowhere to be found in the vendor folder and I just cloned the repo locally and from there manually edited the refenced files but unfortunately if I do go mod tidy and go mod vendor it all dissapears and have to do it all over again. I suppose there is a correct way but do not know it. 

Oh, also tried with the c include path to reference the file seamlessly but it did not work.  

This is the error:
`# github.com/supranational/blst/bindings/go
../../vendor/github.com/supranational/blst/bindings/go/blst.go:16:11: fatal error: 'blst.h' file not found
 #include "blst.h"
          ^~~~~~~~
1 error generated.`

**Comment by Dimitar-St** [comment]
Okay sorry to bother you, I found that I did not set the flags correctly but still do not believe that the correct way of building the project. 
So to summaraize what I did just exported the CGO_FLAGS with this values:
`CGO_CFLAGS="-I/path/to/cloned-lib/blst/src/ -I/path/to/cloned-lib/blst/bindings/ -I/path/to/cloned-lib/blst/build/"`

**Comment by patrick-ogrady** [comment]
Please refer to the "Troubleshooting" section of the README.

In my experience, most BLST errors are resolved as soon as GCC is correctly installed.

You shouldn't need to provide any custom CGO_FLAGS for your development.

What OS are you using?

**Comment by Dimitar-St** [comment]
Right now I am on Mac.

**Comment by Dimitar-St** [comment]
Hello @patrick-ogrady,
Made a sample PR to my forked repo just to see if thats the idea you are talking about (https://github.com/Dimitar-St/hypersdk/pull/1). Will greatly appreciate it if you get me some feedback. Its a rough PR for now because I am having some problem with my machine which is impacting my coding performance.

**Comment by Dimitar-St** [comment]
> Hello @patrick-ogrady,
> 
> Made a sample PR to my forked repo just to see if thats the idea you are talking about (https://github.com/Dimitar-St/hypersdk/pull/1). Will greatly appreciate it if you get me some feedback. Its a rough PR for now because I am having some problem with my machine which is impacting my coding performance. 
> 
>  

Happy New year! @patrick-ogrady

**Comment by patrick-ogrady** [comment]
I think you are on the right track with the `testing` package extraction 👍. I recommend checking out https://github.com/ava-labs/teleporter/blob/main/tests/local/network.go for some more ideas (which IMO has one of the cleaner avalanche network initializations out there).

The big question IMO will be how generic you need to make the initializer (for example, your genesis impl is pretty hardcoded to `tokenvm`). I think it would make sense to settle on some sort of `vm` interface that any HyperVM can implement to get integration test support instead of adding a bunch of `funcs` to the initializer (like I did with `spam`, which is pretty ugly): https://github.com/ava-labs/hypersdk/blob/ad3ac9427c178c85cc55e5dbc9b044b04152d89e/cli/spam.go#L48-L57.

**Comment by Dimitar-St** [comment]
Okay, I got you. I was thinking the same thing as we have a instance struct from where I can extract that into a common interface. Thanks a lot for the feedback.

**Comment by aaronbuchwald** [comment]
Replaced by https://github.com/ava-labs/hypersdk/issues/1090
