### ISSUE TITLE
How to submit two transactions in the integration tests(morpheusvm as template)

### ISSUE THREAD

**Issue by bianyuanop** [ava-labs/hypersdk#376]
i'm writing integration tests for my project. I met an issue that when i tried to submit two transactions, the vm reports duplicate transactions.

codes can be found here: https://github.com/bianyuanop/oraclevm/blob/main/tests/integration/integration_test.go#L782

what i'm trying to do here is to submit two transactions, then build a block. Those two transactions do not look the same to me since the payload is different.

**Comment by patrick-ogrady** [comment]
👋 Your issue is that the first action in the "submitting two transactions" test (https://github.com/bianyuanop/oraclevm/blob/1a5932933dfe8c9393638f25ad7e116c57c8fac6/tests/integration/integration_test.go#L786-L796) is a duplicate of the action you submitted in the previous test (https://github.com/bianyuanop/oraclevm/blob/1a5932933dfe8c9393638f25ad7e116c57c8fac6/tests/integration/integration_test.go#L742-L752), not that it is a duplicate of the other transaction you are trying to include in the block. By default, you cannot submit a duplicate tx within a 60s rolling range.

If you change this (https://github.com/bianyuanop/oraclevm/blob/1a5932933dfe8c9393638f25ad7e116c57c8fac6/tests/integration/integration_test.go#L790-L794) to any other price, modify the tx time using a `timeModifier` (https://github.com/ava-labs/hypersdk/blob/f99184346b94dc7a2956916034be4f19091a3e97/cli/spam.go#L258C5-L258C5), or sleep for 2s (to force a new time without manual modification), it'll work.

**Comment by bianyuanop** [comment]
Thanks so much!
