### ISSUE TITLE
[chain] Only Include Tx Hashes in Blocks

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#540]
Clients should gossip new transactions to all nodes (and never re-gossip). If transactions are not found, we should be able to fetch them from random validators on verification. We can include `txID, size` per tx in the block so we can know how many missing txIDs to request at once.

This would increase the number of transactions that could be referenced in a block from ~7k on the TokenVM to ~50k.

We likely want to move away from targeted gossip because we want to make the producer list much more random (maybe even not possible to compute).

**Comment by patrick-ogrady** [comment]
To make sure we don't get tricked into refetching bad txs, we should keep an invalidity cache.

This will also help us quickly reject blocks that contain bad txs before attempting to fetch things.

**Comment by patrick-ogrady** [comment]
This approach would also mean that all issues related to signature verification sequencing could be removed (prioritization of jobs, verify during parse, etc).

**Comment by patrick-ogrady** [comment]
Do we need to keep an unbounded list of transactions around in case we accept one?

**Comment by patrick-ogrady** [comment]
Would it be trivial for a node to withhold txs they reference to cause frequent instability?

Because of the way the ProposerVM works, it seems like a single proposer could cause 5s block sputters.

**Comment by patrick-ogrady** [comment]
We'd probably want to trigger tx pulling in ParseBlock (prioritizing requests by lowest height).

**Comment by patrick-ogrady** [comment]
To avoid massive compaction, we probably want to prefix all txIDs with the block height.

**Comment by patrick-ogrady** [comment]
When updating a block on other nodes, should pass previous block multi-signature ("ratify") or just pass new block ("abandon").

**Comment by patrick-ogrady** [comment]
May need to require nodes with no stake to gossip randomly, otherwise, it will be trivial to Sybil attack this "one proposal per node" mechanism.

**Comment by patrick-ogrady** [comment]
As soon as we start voting over blobs, it becomes pretty easy for those blobs to become full of duplicates (part of original elegance was that validators never gossiped).

**Comment by patrick-ogrady** [comment]
We could use the value of the Multi-Signature to know who to fetch tx hashes from if we don't have them (if somehow incorporated into the block).

**Comment by aaronbuchwald** [comment]
It would be interesting to try out the idea proposed by Narwahl Tusk: https://arxiv.org/pdf/2105.11827.pdf (thought I came to this independently and realized my line of thinking was pretty close to Narwahl).

For the HyperSDK mempool, it could consist of each honest validator broadcasting a signed message that contains a monotonically increasing counter, a batch of new transactions, and a "view certificate".

The view certificate would contain a vector containing the last broadcast received from each validator and a hash of the broadcast message

For example, `[(5, hash(broadcast from node0) ..., (6, hash(broadcast from nodeN))]` (note this makes conflicting broadcasts easily detectable by the network since a validator should only ever sign a single message for a given round).

A byzantine node has three options: sent a correct broadcast, sign an invalid broadcast (easily detectable), or send only correct broadcasts, but distribute it to only a subsection of the network.

In the optimistic path, every node sends honest broadcasts and there are no discrepancies observed in view certificates sent by the network. As a result, if the block builder sends a view certificate with its block and the peer has seen the latest message in each entry of the vector, then it has also received all of the transactions thus far. If desired, you could also add a deterministic commitment rule given a view certificate that determines exactly which transactions should be committed and in what order, so that we could shrink the block size even further from including all of the transaction hashes to including a merkle root (although the Narwahl Tusk paper mentions they were not able to push the system to the point where the size of transaction hashes was the bottleneck).

If the block builder's view certificate contains round numbers that we have not yet seen locally, then we need to request transactions from either the block builder (which falls back to the case where a large amount of the load falls on the block builder) or from any node in the network that has sent us a view certificate referencing a broadcast received from that peer in that round. Since we have a view certificate from each peer with the last round they've observed of each peer in the network, we know exactly which peers claim to have seen the transaction that we can fetch it from.

Additionally, if our node has already received 2f + 1 view certificates from peers that have seen the same missing messages with round numbers we haven't observed yet, then we already have 2f + 1 signatures attesting to those transactions being available on the network.

This leads to a simple rule for transaction inclusion within a block. A transaction hash is valid to include iff the broadcast  that originated that transactions has received a quorum of 2f + 1 views. The view certificate supplied by the block builder shows its own view of exactly which 2f + 1 or more nodes have seen transactions and each peer can locally confirm that it has received 2f + 1 view certificates to authenticate transaction availability as well.

Signed views could serve as an alternative to generating a multi-signature to prove transaction availability.

Still need to think more about what rules there should be for transaction inclusion in the mempool (enforced by each validator on its own local view) and for inclusion within a block (enforced by the block builder and each node in the network, when it receives a block).

**Comment by mtgnoah** [comment]
@aaronbuchwald I was also looking into Narwhal for HyperSDK but I haven't gotten a chance to start on the code yet. I wonder if this issue could be combined with #579 because that could help reduce the amount of latency.

**Comment by aaronbuchwald** [comment]
> @aaronbuchwald I was also looking into Narwhal for HyperSDK but I haven't gotten a chance to start on the code yet. I wonder if this issue could be combined with #579 because that could help reduce the amount of latency.

I think they may have similar goals, but the changes are pretty well separated, so probably does not make sense to combine them imo.

**Comment by patrick-ogrady** [comment]
If there is a mechanism for deterministically including txs in some root, we could just include roots in each block and add many more txs (as each root could correspond to 2 MB of distributed txs).

**Comment by mtgnoah** [comment]
> If there is a mechanism for deterministically including txs in some root, we could just include roots in each block and add many more txs (as each root could correspond to 2 MB of distributed txs).

Would you be able to use a NMT(https://github.com/celestiaorg/nmt)? It enables Merkle inclusion proofs to be created that prove to a verifier that all the elements of the tree for a specific namespace have been included in a Merkle inclusion proof. It's developed by Celestia.

**Comment by mtgnoah** [comment]
> It would be interesting to try out the idea proposed by Narwahl Tusk: https://arxiv.org/pdf/2105.11827.pdf (thought I came to this independently and realized my line of thinking was pretty close to Narwahl).
> 
> For the HyperSDK mempool, it could consist of each honest validator broadcasting a signed message that contains a monotonically increasing counter, a batch of new transactions, and a "view certificate".
> 
> The view certificate would contain a vector containing the last broadcast received from each validator and a hash of the broadcast message
> 
> For example, `[(5, hash(broadcast from node0) ..., (6, hash(broadcast from nodeN))]` (note this makes conflicting broadcasts easily detectable by the network since a validator should only ever sign a single message for a given round).
> 
> A byzantine node has three options: sent a correct broadcast, sign an invalid broadcast (easily detectable), or send only correct broadcasts, but distribute it to only a subsection of the network.
> 
> In the optimistic path, every node sends honest broadcasts and there are no discrepancies observed in view certificates sent by the network. As a result, if the block builder sends a view certificate with its block and the peer has seen the latest message in each entry of the vector, then it has also received all of the transactions thus far. If desired, you could also add a deterministic commitment rule given a view certificate that determines exactly which transactions should be committed and in what order, so that we could shrink the block size even further from including all of the transaction hashes to including a merkle root (although the Narwahl Tusk paper mentions they were not able to push the system to the point where the size of transaction hashes was the bottleneck).
> 
> If the block builder's view certificate contains round numbers that we have not yet seen locally, then we need to request transactions from either the block builder (which falls back to the case where a large amount of the load falls on the block builder) or from any node in the network that has sent us a view certificate referencing a broadcast received from that peer in that round. Since we have a view certificate from each peer with the last round they've observed of each peer in the network, we know exactly which peers claim to have seen the transaction that we can fetch it from.
> 
> Additionally, if our node has already received 2f + 1 view certificates from peers that have seen the same missing messages with round numbers we haven't observed yet, then we already have 2f + 1 signatures attesting to those transactions being available on the network.
> 
> This leads to a simple rule for transaction inclusion within a block. A transaction hash is valid to include iff the broadcast that originated that transactions has received a quorum of 2f + 1 views. The view certificate supplied by the block builder shows its own view of exactly which 2f + 1 or more nodes have seen transactions and each peer can locally confirm that it has received 2f + 1 view certificates to authenticate transaction availability as well.
> 
> Signed views could serve as an alternative to generating a multi-signature to prove transaction availability.
> 
> Still need to think more about what rules there should be for transaction inclusion in the mempool (enforced by each validator on its own local view) and for inclusion within a block (enforced by the block builder and each node in the network, when it receives a block).

Would the signed views use Reed Solomon Encoding or not? I wonder if it is worth looking into verifiable information dispersal as listed in these 2 papers https://arxiv.org/abs/2111.12323 and https://eprint.iacr.org/2021/1500 They detail how you can split the data between nodes so recoverability is ensured essentially. It's an alternative to Data Availability Sampling that is more efficient.

**Comment by mtgnoah** [comment]
Celestia also took a jab at this issue as detailed here: https://github.com/celestiaorg/celestia-core/blob/1ce8926431429a4390dcb201828c853b5155ca30/mempool/cat/spec.md

**Comment by mtgnoah** [comment]
> Celestia also took a jab at this issue as detailed here: https://github.com/celestiaorg/celestia-core/blob/1ce8926431429a4390dcb201828c853b5155ca30/mempool/cat/spec.md

Actually not this exact issue. CAT could help with throughput for this. Similar to Narwhal.

**Comment by mtgnoah** [comment]
Here is a great article on different types of Merkle trees to potentially use for proving inclusion. https://maven11.substack.com/p/from-linked-lists-to-namespace-merkle

**Comment by patrick-ogrady** [comment]
I'm writing up a spec with my ideas.
