### ISSUE TITLE
[x/programs/rust] Add support for non fixed length program function args. 

### ISSUE THREAD

**Issue by hexfusion** [ava-labs/hypersdk#576]
We should be able to simplify the signature of a HyperSDK program that accepts arbitrary length strings. Perhaps add functionality to `Argument` or make a new type that takes the 2 params  `ptr` and  `len` and handles the memory access in the background. Today this is possible but requires 2 params on the signature for each. 

Another alternative might be using the first byte for length prefix.

### today
```rust
pub fn init(program: Program, name_ptr: i32, name_len:i32) -> bool {
```
### desired
```rust
pub fn init(program: Program, name: Argument) -> bool {
    program
        .state()
        .store(StateKey::Name, name.to_bytes())
        .expect("failed to store coin name");
}
```

**Comment by exdx** [comment]
I agree. Passing in multiple params gets pretty unwieldy. More than 8 params is a clippy lint violation I believe.

**Comment by hexfusion** [comment]
Ideally we are dealing with objects via Borsh I suspect.

**Comment by richardpringle** [comment]
In your example, `Name` should be a string and the `public` macro should provide all of the logic to fetch the pointer or deserialize, or whatever needs to happen. We should not restrict the types that can be used in the function signature beyond requiring a specific trait implementation (marker-trait or otherwise).

Thoughts?

**Comment by richardpringle** [comment]
> It would be non trivial to update the macro to support `String` of arbitrary length. Because from the go side we would need to pass in two arguments anyway(ptr + length) and then our macro would need to: squash the function signature & complete the conversion. Would it make sense to have a variable say `String32` that is a null terminated string with a fixed length like `32` or `64`? This is kinda what I already do with the `Bytes32` type
> 
> Also: the macro calls `.into()` to convert from an`int` to the user specified type so we would need extra handling for two arguments coming from go. Maybe we can serialize the length as a prefix of the string and deserialize in our macro?

Makes sense. Seems like serialization should solve this? Looks like borsh encodes strings lengths, so that should work?

**Comment by samliok** [comment]
> Makes sense. Seems like serialization should solve this? Looks like borsh encodes strings lengths, so that should work?

I think a good solution would be to update the public macro so that it automatically deserializes into the function arguments. 

So at a high level a user would specify 

```rust
pub fn do_something(program: Program, name: String, object: CustomUserObject) {
 ```

and the `public` macro would expose this signature to the host.
```rust
pub fn_do_somthing_guest(programPtr: i64, programLength: i64, namePtr: i64, objectPtr: i64, objectLength: i64) 
```
 behind the scenes the `public` macro would first convert each int pairing to bytes, and then deserialize them into the needed type.

**Comment by samliok** [comment]
On second thought, I don't think this would work because borsh might not serialize/deserialize arguments in rust/go in the same way.

**Comment by richardpringle** [comment]
> On second thought, I don't think this would work because borsh might not serialize/deserialize arguments in rust/go in the same way.

I think it should. Determinism is part of the spec, right?
