### ISSUE TITLE
[x/programs] cannot run golang example tests

### ISSUE THREAD

**Issue by najeal** [ava-labs/hypersdk#882]
I don't know if it is the right way to do it but:
- running : `cargo build --target wasm32-unknown-unknown` in rust counter example
- moving the count.wasm file into fixtures
- run `go test -run TestCounterProgram` in go counter example

I get this error:
```
counter_test.go:62
Error: Received unexpected error:
           incompatible import type for `state::get`

           Caused by:
              function types incompatible: expected func of type `(i64, i64) -> (i64)`, found func of type `(i32, i32, i32, i32) -> (i32)`
Test:   TestCounterProgram
```

**Comment by iFrostizz** [comment]
This is probably because of the recent merge of https://github.com/ava-labs/hypersdk/pull/872 and you could have kept the old compiled target, did you moved the compiled binary from `x/programs/rust/examples/token/build/wasm32-unknown-unknown/release/token.wasm` ? to `x/programs/tests/fixture/` (also make sure that you compile using --release)

**Comment by najeal** [comment]
Thank for your answer !
Yes I was moving the compiled binary into `fixture`.
Tried with `--release` after a restart, issue looks resolved and not reproducible anymore 😶
