### ISSUE TITLE
Export Blocks/Transactions/State Diffs to External Store

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/hypersdk#961]
Add support for reliable streaming of block/state transactions to external storage. HyperSDK will never service archival information over the RPC (just optionally current state).

**Comment by patrick-ogrady** [comment]
Related: #531

**Comment by patrick-ogrady** [comment]
Previous work: https://github.com/ava-labs/hypersdk/pull/697

**Comment by kpachhai** [comment]
Any update on this?

**Comment by aaronbuchwald** [comment]
Posted updated thoughts on a slightly different direction here: https://github.com/ava-labs/hypersdk/issues/1225.

The idea would be to find a different middle ground where the HyperSDK can serve APIs to make it as easy as possible to get started, but push towards an external service for high performance use cases rather than trying to heavily optimize any in-node APIs.

**Comment by aaronbuchwald** [comment]
Closing in favor of https://github.com/ava-labs/hypersdk/issues/1226 and https://github.com/ava-labs/hypersdk/issues/1225
